### ISSUE TITLE
Sourcemaps support

### ISSUE THREAD

**Issue by Toilal** [ZhongxuYang/vite-plugin-version-mark#10]
When using the plugin, the following warning is displayed.

(vite-plugin-version-mark plugin) Sourcemap is likely to be incorrect: a plugin (vite-plugin-version-mark) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help

**Comment by scris** [comment]
The same for me.

**Comment by ZhongxuYang** [comment]
hi 👋 @Toilal @scris , I just updated [v0.0.13](https://www.npmjs.com/package/vite-plugin-version-mark) to fix this issue. 

Thank you for your feedback~🎉

**Comment by scris** [comment]
> hi 👋 @Toilal @scris , I just updated [v0.0.13](https://www.npmjs.com/package/vite-plugin-version-mark) to fix this issue.
> 
> Thank you for your feedback~🎉

Oh, thank you so much for your work 🙏
