### ISSUE TITLE
Allow to add version field into manifest.json

### ISSUE THREAD

**Issue by awesome-manuel** [ZhongxuYang/vite-plugin-version-mark#12]
Just as this plugin can inject a `<meta>` tag into `index.html` it should as well allow to inject `version` into `manifest.json`.

**Comment by ZhongxuYang** [comment]
Sorry I'm not familiar with WebExtension, if anyone is willing to contribute a PR I'd be happy to merge it.

**Comment by ZhongxuYang** [comment]
Hi! 👋

Now we can do this by configuring the `outputFile` function in `v0.1.2`. See the [configuration](https://github.com/ZhongxuYang/vite-plugin-version-mark#outputfile-configuration-option).
