### ISSUE TITLE
Version not available in `library` mode

### ISSUE THREAD

**Issue by Lonli-Lokli** [ZhongxuYang/vite-plugin-version-mark#5]
No version field is available when you are building with this plugin and use `vite`'s library mode

**Comment by ZhongxuYang** [comment]
hello 👋， Sorry for the delay in replying to you!

I just updated version 0.0.11 to address this issue. Added the ifExport configuration item to export version information in the entry file. I'm not sure if this will solve your problem. If necessary, please feedback or PR. 😊

This is a very useful suggestion, thank you very much! 🎉
