### ISSUE TITLE
ambiguous `ifShortSHA` 

### ISSUE THREAD

**Issue by littlecxm** [ZhongxuYang/vite-plugin-version-mark#8]
https://github.com/ZhongxuYang/vite-plugin-version-mark/blob/7d98356946123a8e67f239dc60d949d0960c44e7/src/plugins/core/main.ts#L67

如果我想使用  `ifShortSHA` 那我必须在使用之前设置 `ifGitSHA: true`
是否考虑 `ifGitSHA` -> `UseGitSHA?`

**Comment by ZhongxuYang** [comment]
Indeed, these two attributes can easily cause confusion in their use.


I think `ifGitSHA` -> `UseGitSHA` cannot allow existing users to upgrade smoothly.
Therefore it may be a more friendly design to remove the impact of `ifGitSHA` on `ifShortSHA` (that is, you can enable ShortSHA by only setting `ifShortSHA: true`).


According to this, the priority of the modified version field will be: `command` > `ifShortSHA ` > `ifGitSHA` > `version`.


---

确实这两个属性容易造成使用的困惑。

我认为 `ifGitSHA` -> `UseGitSHA` 没办法让现有的使用者平滑升级。
因此去除 `ifGitSHA ` 对 `ifShortSHA` 的影响可能会是更友好的设计（也就是可以通过只设置 `ifShortSHA: true` 来启用ShortSHA）。

按照这样，修改后的版本字段的优先级会是：`command` > `ifShortSHA ` > `ifGitSHA` > `version`。

**Comment by ZhongxuYang** [comment]
Hi！👋

刚刚已经更新了 [v0.0.12](https://github.com/ZhongxuYang/vite-plugin-version-mark/releases)，按照上面的回复处理了这个问题。如果有别的想法欢迎继续交流～

感谢建议！🎉

**Comment by littlecxm** [comment]
感谢修复～
